// dirs=`ls -1 ../libsrc | grep -v crt0 | grep -v math`; for d in $dirs; do ls -1 ../libsrc/$d/*.c | ruby -ne 'puts "#include <#{$_.chomp}>"'; done

#include <../libsrc/misc/basename.c>
#include <../libsrc/misc/dirname.c>
#include <../libsrc/misc/errno.c>
#include <../libsrc/misc/getopt.c>
#include <../libsrc/misc/isalnum.c>
#include <../libsrc/misc/isalpha.c>
#include <../libsrc/misc/isdigit.c>
#include <../libsrc/misc/isspace.c>
#include <../libsrc/misc/isxdigit.c>
#include <../libsrc/misc/longjmp.c>
#include <../libsrc/misc/rng_xor64.c>
#include <../libsrc/misc/setjmp.c>
#include <../libsrc/misc/tolower.c>
#include <../libsrc/misc/toupper.c>
#include <../libsrc/stdio/assert.c>
#include <../libsrc/stdio/fclose.c>
#include <../libsrc/stdio/fgetc.c>
#include <../libsrc/stdio/fgets.c>
#include <../libsrc/stdio/fileno.c>
#include <../libsrc/stdio/fopen.c>
#include <../libsrc/stdio/fprintf.c>
#include <../libsrc/stdio/fputc.c>
#include <../libsrc/stdio/fputs.c>
#include <../libsrc/stdio/fread.c>
#include <../libsrc/stdio/fseek.c>
#include <../libsrc/stdio/ftell.c>
#include <../libsrc/stdio/fwrite.c>
#include <../libsrc/stdio/getc.c>
#include <../libsrc/stdio/getchar.c>
#include <../libsrc/stdio/getline.c>
#include <../libsrc/stdio/perror.c>
#include <../libsrc/stdio/printf.c>
#include <../libsrc/stdio/remove.c>
#include <../libsrc/stdio/snprintf.c>
#include <../libsrc/stdio/sprintf.c>
#include <../libsrc/stdio/stdin.c>
#include <../libsrc/stdio/tmpfile.c>
#include <../libsrc/stdio/vprintf.c>
#include <../libsrc/stdio/vfprintf.c>
#include <../libsrc/stdio/vsnprintf.c>
#include <../libsrc/stdio/vsprintf.c>
#include <../libsrc/stdlib/atoi.c>
#include <../libsrc/stdlib/calloc.c>
#include <../libsrc/stdlib/drand48.c>
#include <../libsrc/stdlib/erand48.c>
#include <../libsrc/stdlib/exit.c>
#include <../libsrc/stdlib/malloc.c>
#include <../libsrc/stdlib/mkstemp.c>
#include <../libsrc/stdlib/mkstemps.c>
#include <../libsrc/stdlib/qsort.c>
#include <../libsrc/stdlib/realloc.c>
#include <../libsrc/string/memchr.c>
#include <../libsrc/string/memcmp.c>
#include <../libsrc/string/memcpy.c>
#include <../libsrc/string/memmove.c>
#include <../libsrc/string/memset.c>
#include <../libsrc/string/strcasecmp.c>
#include <../libsrc/string/strcat.c>
#include <../libsrc/string/strchr.c>
#include <../libsrc/string/strcmp.c>
#include <../libsrc/string/strcpy.c>
#include <../libsrc/string/strdup.c>
#include <../libsrc/string/strlen.c>
#include <../libsrc/string/strncasecmp.c>
#include <../libsrc/string/strncat.c>
#include <../libsrc/string/strncmp.c>
#include <../libsrc/string/strncpy.c>
#include <../libsrc/string/strndup.c>
#include <../libsrc/string/strrchr.c>
#include <../libsrc/string/strstr.c>
#include <../libsrc/string/strtod.c>
#include <../libsrc/string/strtol.c>
#include <../libsrc/string/strtoul.c>
#include <../libsrc/unistd/brk.c>
#include <../libsrc/unistd/chmod.c>
#include <../libsrc/unistd/close.c>
#include <../libsrc/unistd/dup.c>
#include <../libsrc/unistd/execve.c>
#include <../libsrc/unistd/execvp.c>
#include <../libsrc/unistd/fork.c>
#include <../libsrc/unistd/getcwd.c>
#include <../libsrc/unistd/getrandom.c>
#include <../libsrc/unistd/ioctl.c>
#include <../libsrc/unistd/isatty.c>
#include <../libsrc/unistd/kill.c>
#include <../libsrc/unistd/lseek.c>
#include <../libsrc/unistd/open.c>
#include <../libsrc/unistd/pipe.c>
#include <../libsrc/unistd/read.c>
#include <../libsrc/unistd/unlink.c>
#include <../libsrc/unistd/wait4.c>
#include <../libsrc/unistd/waitpid.c>
#include <../libsrc/unistd/write.c>
